
services:
  mysql:
    image: mysql:8.0
    container_name: rezabots-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rezabots
      MYSQL_USER: mahdi
      MYSQL_PASSWORD: 123
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
